changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bugs 🐞
      labels:
        - bug
    - title: Squashed Bugs 🐞
      labels:
        - bug-fix
    - title: Documentation 📖
      labels:
        - "documentation"
    - title: Asked questions ❓
      labels:
        - "questions"
    - title: Other Changes
      labels:
        - "*"
